name: Nuget publish

on:
  push:
    branches: [ master ]
    paths:
      - 'version'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Create the package
      run:  dotnet pack --configuration Release src/EasyTest/EasyTest.csproj -p:Version=$(cat version)
    - name: Publish the package to microsoft nuget repository
      run: dotnet nuget push src/EasyTest/bin/Release/*.nupkg --api-key ${{secrets.NUGET_AUTH_TOKEN}} --source https://api.nuget.org/v3/index.json
